const $ = (selector) => document.querySelector(selector);
const money = (value) => `${Math.round(Number(value) || 0).toLocaleString('ru-RU')} в‚ё`;
const defaultMenu = [
  ['РҐРѕР»РѕРґРЅС‹Рµ Р·Р°РєСѓСЃРєРё', 'РњСЏСЃРЅРѕРµ, СЃС‹СЂРЅРѕРµ Рё РѕРІРѕС‰РЅРѕРµ Р°СЃСЃРѕСЂС‚Рё', 75000],
  ['РЎР°Р»Р°С‚С‹', '2вЂ“3 СЃР°Р»Р°С‚Р° РЅР° РѕР±С‰РёР№ СЃС‚РѕР»', 54000],
  ['Р“РѕСЂСЏС‡РёРµ Р·Р°РєСѓСЃРєРё', 'РњРёРЅРё-С€Р°С€Р»С‹С‡РєРё Рё Р¶СЋР»СЊРµРЅ', 51000],
  ['РћСЃРЅРѕРІРЅРѕРµ Р±Р»СЋРґРѕ', 'РњСЏСЃРѕ РёР»Рё СЂС‹Р±Р° СЃ РіР°СЂРЅРёСЂРѕРј', 135000],
  ['РќР°РїРёС‚РєРё', 'Р‘РµР·Р°Р»РєРѕРіРѕР»СЊРЅС‹Рµ РЅР°РїРёС‚РєРё, С‡Р°Р№, РєРѕС„Рµ', 45000],
  ['РђР»РєРѕРіРѕР»СЊ', 'Р’РёРЅРѕ, РёРіСЂРёСЃС‚РѕРµ Рё РєСЂРµРїРєРёРµ РЅР°РїРёС‚РєРё', 105000],
];
const defaultTasks = ['РЈС‚РѕС‡РЅРёС‚СЊ СЃРІРѕР±РѕРґРµРЅ Р»Рё Р·Р°Р» РЅР° 7 РЅРѕСЏР±СЂСЏ', 'Р’РЅРµСЃС‚Рё РїСЂРµРґРѕРїР»Р°С‚Сѓ Р·Р° РїР»РѕС‰Р°РґРєСѓ', 'РЎРѕРіР»Р°СЃРѕРІР°С‚СЊ РјРµРЅСЋ Рё СЃРµСЂРІРёСЃРЅС‹Р№ СЃР±РѕСЂ', 'Р—Р°РєР°Р·Р°С‚СЊ С‚РѕСЂС‚', 'РћС‚РїСЂР°РІРёС‚СЊ РїСЂРёРіР»Р°С€РµРЅРёСЏ', 'РЎРѕР±СЂР°С‚СЊ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ РіРѕСЃС‚РµР№', 'РџРѕРґРіРѕС‚РѕРІРёС‚СЊ РїР»РµР№Р»РёСЃС‚ 90-С…', 'РџСЂРѕРІРµСЂРёС‚СЊ С‚Р°РЅС†РїРѕР» Рё Р·РІСѓРє Р·Р° 3 РґРЅСЏ'];
const state = { menu: structuredClone(defaultMenu), tasks: defaultTasks.map((text) => ({ text, done: false })) };

function getData() { return { celebrant: $('#celebrant').value.trim() || 'РёРјРµРЅРёРЅРЅРёРє', city: $('#city').value.trim() || 'РіРѕСЂРѕРґ', date: $('#event-date').value, start: $('#start-time').value, end: $('#end-time').value, guests: Math.max(1, Number($('#guest-count').value) || 1), perPerson: Math.max(0, Number($('#per-person').value) || 0), venue: $('#venue').value.trim() || 'РїР»РѕС‰Р°РґРєР°', address: $('#venue-address').value.trim(), music: $('#music-style').value, separateService: $('#service-separate').checked, service: Math.max(0, Number($('#service-percent').value) || 0), cake: Math.max(0, Number($('#cake-cost').value) || 0) }; }
function formattedDate(value) { if (!value) return 'СѓС‚РѕС‡РЅСЏРµС‚СЃСЏ'; return new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${value}T12:00:00`)); }
function duration(start, end) { if (!start || !end) return 0; let a = start.split(':').map(Number), b = end.split(':').map(Number); let minutes = b[0] * 60 + b[1] - (a[0] * 60 + a[1]); if (minutes <= 0) minutes += 1440; return Math.round(minutes / 60 * 10) / 10; }
function addMinutes(time, minutes) { let [h,m] = time.split(':').map(Number); const total = (h * 60 + m + minutes) % 1440; return `${String(Math.floor(total / 60)).padStart(2,'0')}:${String(total % 60).padStart(2,'0')}`; }

function updateSummary() { const d = getData(), base = d.guests * d.perPerson, service = d.separateService ? base * d.service / 100 : 0, total = base + service + d.cake; $('#summary-guests').textContent = d.guests; $('#summary-budget').textContent = money(base); $('#summary-duration').textContent = `${duration(d.start, d.end)} С‡.`; $('#summary-venue').textContent = d.venue; $('#food-total').textContent = money(base * .60); $('#drink-total').textContent = money(base * .25); $('#reserve-total').textContent = money(base * .15); $('#budget-donut').innerHTML = `${Math.round(base / 1000)}<br><small>С‚С‹СЃ. в‚ё</small>`; $('#grand-total').textContent = money(total); $('#budget-note').textContent = d.separateService ? `Р±Р°РЅРєРµС‚ + СЃРµСЂРІРёСЃ ${d.service}% + С‚РѕСЂС‚` : 'Р±Р°РЅРєРµС‚ + С‚РѕСЂС‚'; }
function invitationText(style) { const d = getData(); const details = `рџ“… ${formattedDate(d.date)}\nрџ•– ${d.start}\nрџ“Ќ ${d.venue}${d.address ? `, ${d.address}` : ''}`; const options = { warm: `Р”РѕСЂРѕРіРёРµ РґСЂСѓР·СЊСЏ! вњЁ\n\nРЈ РјРµРЅСЏ РµСЃС‚СЊ РѕС‚Р»РёС‡РЅС‹Р№ РїРѕРІРѕРґ СЃРѕР±СЂР°С‚СЊ РІСЃРµС… Р»СЋР±РёРјС‹С… Р»СЋРґРµР№ РІРјРµСЃС‚Рµ вЂ” РјРѕР№ РґРµРЅСЊ СЂРѕР¶РґРµРЅРёСЏ!\n\n${details}\n\nР’Р°СЃ Р¶РґСѓС‚ РїСЂР°Р·РґРЅРёС‡РЅС‹Р№ СѓР¶РёРЅ, Р»СЋР±РёРјС‹Рµ С…РёС‚С‹ ${d.music}, С‚Р°РЅС†С‹ Рё РјРЅРѕРіРѕ С‚С‘РїР»С‹С… РјРѕРјРµРЅС‚РѕРІ. рџ’ѓ\n\nРћС‡РµРЅСЊ Р¶РґСѓ РєР°Р¶РґРѕРіРѕ! РџРѕР¶Р°Р»СѓР№СЃС‚Р°, РґР°Р№С‚Рµ Р·РЅР°С‚СЊ, СЃРјРѕР¶РµС‚Рµ Р»Рё РїСЂРёР№С‚Рё.\n\nРЎ Р»СЋР±РѕРІСЊСЋ, ${d.celebrant} рџ’–`, festive: `рџЋ‰ РџР РђР—Р”РќРРљ РќРђР§РРќРђР•РўРЎРЇ! рџЋ‰\n\n${d.celebrant} РїСЂРёРіР»Р°С€Р°РµС‚ РІР°СЃ РѕС‚РјРµС‚РёС‚СЊ СЃРІРѕР№ РґРµРЅСЊ СЂРѕР¶РґРµРЅРёСЏ СЏСЂРєРѕ, РіСЂРѕРјРєРѕ Рё СЃ РѕС‚Р»РёС‡РЅС‹Рј РЅР°СЃС‚СЂРѕРµРЅРёРµРј!\n\n${details}\n\nР’ РїСЂРѕРіСЂР°РјРјРµ РІРµС‡РµСЂР°:\nвњЁ РїСЂР°Р·РґРЅРёС‡РЅС‹Р№ СЃС‚РѕР»\nрџЋ¶ С…РёС‚С‹ ${d.music}\nрџ’ѓ С‚Р°РЅС†С‹ РґРѕ РЅРѕС‡Рё\nрџЋ‚ С‚РѕСЂС‚ Рё СЃР°РјС‹Рµ С‚С‘РїР»С‹Рµ РїРѕР·РґСЂР°РІР»РµРЅРёСЏ\n\nР‘СѓРґСѓ СЃС‡Р°СЃС‚Р»РёРІР° РІРёРґРµС‚СЊ РІР°СЃ СЂСЏРґРѕРј! РџРѕРґС‚РІРµСЂРґРёС‚Рµ, РїРѕР¶Р°Р»СѓР№СЃС‚Р°, СѓС‡Р°СЃС‚РёРµ.\n\n${d.celebrant}`, short: `рџЋ‚ Р”СЂСѓР·СЊСЏ, Р¶РґСѓ РІР°СЃ РЅР° СЃРІРѕС‘Рј РґРЅРµ СЂРѕР¶РґРµРЅРёСЏ!\n\n${details}\n\nР‘СѓРґСѓС‚ РІРєСѓСЃРЅС‹Р№ СѓР¶РёРЅ, РјСѓР·С‹РєР° ${d.music} Рё С‚Р°РЅС†С‹. рџ’ѓ\n\nРќР°РїРёС€РёС‚Рµ, РїРѕР¶Р°Р»СѓР№СЃС‚Р°, СЃРјРѕР¶РµС‚Рµ Р»Рё РїСЂРёР№С‚Рё.\n${d.celebrant} рџ’–` }; return options[style]; }
let currentStyle = 'warm';
function updateInvitation() { $('#invitation-text').value = invitationText(currentStyle); }
function renderMenu() { const body = $('#menu-body'); body.innerHTML = ''; state.menu.forEach((row, index) => { const tr = document.createElement('tr'); tr.innerHTML = `<td><input aria-label="РљР°С‚РµРіРѕСЂРёСЏ" value="${row[0]}" data-row="${index}" data-col="0"></td><td><input aria-label="РџРѕР·РёС†РёСЏ" value="${row[1]}" data-row="${index}" data-col="1"></td><td><input aria-label="РЎСѓРјРјР°" type="number" min="0" value="${row[2]}" data-row="${index}" data-col="2"></td><td><button class="icon-button delete-menu" data-row="${index}" type="button" aria-label="РЈРґР°Р»РёС‚СЊ РїРѕР·РёС†РёСЋ">Г—</button></td>`; body.appendChild(tr); }); updateMenuTotal(); }
function updateMenuTotal() { const total = state.menu.reduce((sum, row) => sum + (Number(row[2]) || 0), 0), limit = getData().guests * getData().perPerson; $('#menu-total').textContent = money(total); $('#menu-warning').textContent = total > limit ? `РџСЂРµРІС‹С€РµРЅРёРµ РЅР° ${money(total-limit)}` : `РћСЃС‚Р°С‚РѕРє ${money(limit-total)}`; }
function playlist() { const style = getData().music; const lists = { '90-С…': ['19:00 вЂ” Р»С‘РіРєРёР№ РїРѕРї Рё РґРёСЃРєРѕ 90-С… РґР»СЏ РІСЃС‚СЂРµС‡Рё РіРѕСЃС‚РµР№', '20:00 вЂ” Р»СЋР±РёРјС‹Рµ СЂСѓСЃСЃРєРёРµ Рё Р·Р°СЂСѓР±РµР¶РЅС‹Рµ С…РёС‚С‹ Р·Р° СѓР¶РёРЅРѕРј', '21:20 вЂ” С‚Р°РЅС†РµРІР°Р»СЊРЅС‹Р№ Р±Р»РѕРє: Ace of Base, Roxette, В«Р СѓРєРё Р’РІРµСЂС…!В», В«РРІР°РЅСѓС€РєРёВ»', '23:00 вЂ” СЃР°РјС‹Рµ СЌРЅРµСЂРіРёС‡РЅС‹Рµ РїРµСЃРЅРё Рё Р·Р°СЏРІРєРё РіРѕСЃС‚РµР№', '00:40 вЂ” РѕР±С‰Р°СЏ С„РёРЅР°Р»СЊРЅР°СЏ РїРµСЃРЅСЏ'], '2000-С…': ['19:00 вЂ” СЃРїРѕРєРѕР№РЅС‹Р№ РїРѕРї 2000-С…', '20:00 вЂ” РёР·РІРµСЃС‚РЅС‹Рµ С‚СЂРµРєРё РґР»СЏ РѕР±С‰РµРЅРёСЏ', '21:20 вЂ” СЌРЅРµСЂРіРёС‡РЅС‹Р№ С‚Р°РЅС†РµРІР°Р»СЊРЅС‹Р№ Р±Р»РѕРє', '23:00 вЂ” РїРµСЃРЅРё РїРѕ Р·Р°СЏРІРєР°Рј', '00:40 вЂ” РѕР±С‰РёР№ С„РёРЅР°Р»'], 'РЎРѕРІСЂРµРјРµРЅРЅС‹Рµ С…РёС‚С‹': ['19:00 вЂ” Р»С‘РіРєРёР№ СЃРѕРІСЂРµРјРµРЅРЅС‹Р№ РїРѕРї', '20:00 вЂ” С„РѕРЅРѕРІР°СЏ РјСѓР·С‹РєР° РґР»СЏ СѓР¶РёРЅР°', '21:20 вЂ” С‚Р°РЅС†РµРІР°Р»СЊРЅС‹Рµ С…РёС‚С‹', '23:00 вЂ” Р°РєС‚РёРІРЅС‹Р№ Р±Р»РѕРє', '00:40 вЂ” РѕР±С‰РёР№ С„РёРЅР°Р»'], 'РЎРјРµС€Р°РЅРЅС‹Р№ РїР»РµР№Р»РёСЃС‚': ['19:00 вЂ” Р»С‘РіРєРёРµ Р·РЅР°РєРѕРјС‹Рµ С…РёС‚С‹', '20:00 вЂ” РјСѓР·С‹РєР° РґР»СЏ РѕР±С‰РµРЅРёСЏ', '21:20 вЂ” 90-Рµ, 00-Рµ Рё СЃРѕРІСЂРµРјРµРЅРЅС‹Рµ С‚Р°РЅС†РµРІР°Р»СЊРЅС‹Рµ С‚СЂРµРєРё', '23:00 вЂ” РїРµСЃРЅРё РїРѕ Р·Р°СЏРІРєР°Рј', '00:40 вЂ” РѕР±С‰РёР№ С„РёРЅР°Р»'] }; $('#playlist-title').textContent = `РҐРёС‚С‹ ${style}`; $('#playlist').innerHTML = lists[style].map((line) => `<li>${line}</li>`).join(''); }
function renderTimeline() { const d = getData(), labels = ['РЎР±РѕСЂ РіРѕСЃС‚РµР№, welcome-РјСѓР·С‹РєР°', 'РџРµСЂРІС‹Рµ С‚РѕСЃС‚С‹ Рё Р·Р°РєСѓСЃРєРё', 'РЈР¶РёРЅ Рё РѕР±С‰РµРЅРёРµ', 'РРіСЂР°: В«РњСѓР·С‹РєР°Р»СЊРЅС‹Р№ СЃС‚РѕРї-РєР°РґСЂВ»', `РўР°РЅС†РµРІР°Р»СЊРЅС‹Р№ Р±Р»РѕРє ${d.music}`, 'РўРѕСЂС‚ Рё РїРѕР·РґСЂР°РІР»РµРЅРёСЏ', 'РЎРІРѕР±РѕРґРЅР°СЏ РїСЂРѕРіСЂР°РјРјР° Рё С‚Р°РЅС†С‹', 'Р¤РёРЅР°Р»СЊРЅР°СЏ РїРµСЃРЅСЏ, С„РѕС‚Рѕ Рё РїСЂРѕРІРѕРґС‹']; const lengths = [30,30,60,20,70,30,100,20]; let time = d.start || '19:00'; $('#timeline').innerHTML = labels.map((label, i) => { const row = `<div class="time-row"><time>${time}</time><div>${label}</div></div>`; time = addMinutes(time, lengths[i]); return row; }).join(''); }
function renderTasks() { $('#checklist').innerHTML = state.tasks.map((task, i) => `<label class="task"><input data-task="${i}" type="checkbox" ${task.done ? 'checked' : ''}><span>${task.text}</span><button class="delete-task" data-delete-task="${i}" type="button" aria-label="РЈРґР°Р»РёС‚СЊ">Г—</button></label>`).join(''); }
function renderAll() { updateSummary(); updateInvitation(); updateMenuTotal(); playlist(); renderTimeline(); }
function persist() { const inputs = {}; document.querySelectorAll('#event-form input, #event-form select, #alcohol, #service-separate, #dance-floor, #service-percent, #cake-cost').forEach(el => inputs[el.id] = el.type === 'checkbox' ? el.checked : el.value); localStorage.setItem('birthday-planner', JSON.stringify({ inputs, menu: state.menu, tasks: state.tasks, style: currentStyle })); }
function restore() { try { const saved = JSON.parse(localStorage.getItem('birthday-planner')); if (!saved) return; Object.entries(saved.inputs || {}).forEach(([id, value]) => { const el = $(`#${id}`); if (el) el.type === 'checkbox' ? el.checked = value : el.value = value; }); if (Array.isArray(saved.menu)) state.menu = saved.menu; if (Array.isArray(saved.tasks)) state.tasks = saved.tasks; currentStyle = saved.style || 'warm'; } catch (_) {} }

restore(); renderMenu(); renderTasks(); renderAll();
document.querySelectorAll('#event-form input, #event-form select, #service-separate, #service-percent, #cake-cost').forEach(el => el.addEventListener('input', () => { renderAll(); persist(); }));
document.querySelectorAll('#event-form input, #event-form select, #service-separate, #service-percent, #cake-cost').forEach(el => el.addEventListener('change', () => { renderAll(); persist(); }));
document.querySelectorAll('.style-button').forEach(button => button.addEventListener('click', () => { currentStyle = button.dataset.style; document.querySelectorAll('.style-button').forEach(b => b.classList.toggle('active', b === button)); updateInvitation(); persist(); }));
$('#copy-invitation').addEventListener('click', async () => { try { await navigator.clipboard.writeText($('#invitation-text').value); $('#copy-status').textContent = 'РЎРєРѕРїРёСЂРѕРІР°РЅРѕ'; } catch { $('#invitation-text').select(); document.execCommand('copy'); $('#copy-status').textContent = 'РЎРєРѕРїРёСЂРѕРІР°РЅРѕ'; } setTimeout(() => $('#copy-status').textContent = '', 1800); });
$('#menu-body').addEventListener('input', e => { if (!e.target.dataset.row) return; const row = Number(e.target.dataset.row), col = Number(e.target.dataset.col); state.menu[row][col] = col === 2 ? Number(e.target.value) || 0 : e.target.value; updateMenuTotal(); persist(); });
$('#menu-body').addEventListener('click', e => { const btn = e.target.closest('.delete-menu'); if (!btn) return; state.menu.splice(Number(btn.dataset.row), 1); renderMenu(); persist(); });
$('#add-menu-row').addEventListener('click', () => { state.menu.push(['Р”СЂСѓРіРѕРµ', 'РќРѕРІР°СЏ РїРѕР·РёС†РёСЏ', 0]); renderMenu(); persist(); });
$('#checklist').addEventListener('change', e => { if (e.target.dataset.task === undefined) return; state.tasks[Number(e.target.dataset.task)].done = e.target.checked; persist(); });
$('#checklist').addEventListener('click', e => { const btn = e.target.closest('[data-delete-task]'); if (!btn) return; state.tasks.splice(Number(btn.dataset.deleteTask), 1); renderTasks(); persist(); });
$('#add-task').addEventListener('click', () => { const input = $('#new-task'), text = input.value.trim(); if (!text) return; state.tasks.push({ text, done: false }); input.value = ''; renderTasks(); persist(); });
$('#new-task').addEventListener('keydown', e => { if (e.key === 'Enter') { e.preventDefault(); $('#add-task').click(); } });
$('#save-plan').addEventListener('click', () => { persist(); const btn = $('#save-plan'); const label = btn.textContent; btn.textContent = 'РЎРѕС…СЂР°РЅРµРЅРѕ'; setTimeout(() => btn.textContent = label, 1600); });
$('#print-plan').addEventListener('click', () => window.print());
$('#new-event').addEventListener('click', () => { if (confirm('РЎРѕР·РґР°С‚СЊ РЅРѕРІС‹Р№ РїР»Р°РЅ? РўРµРєСѓС‰РёР№ С‡РµСЂРЅРѕРІРёРє Р±СѓРґРµС‚ СЃР±СЂРѕС€РµРЅ.')) { localStorage.removeItem('birthday-planner'); location.reload(); } });

